### ISSUE TITLE
私人问题？

### ISSUE THREAD

**Issue by generalzhang** [Usey95/Usey95.github.io#1]
我是张丽君，以前你是否在伦中读初中？

**Comment by Usey95** [comment]
是啊，你怎么找到我的。。

**Comment by generalzhang** [comment]
因为我最近也在v2ex找工作，同样也是前端，碰到你的简历-->名字-->个人网页-->github，你的名字重复性不强，就你啦。就是有点惊到了。

**Comment by Usey95** [comment]
我已经找到工作了，微信:dearpork520，你加下我吧
